version: '3.8'

services:
  backend:
    container_name: backend
    restart: always
    build:
      context: ./config_services
      dockerfile: Containerfile
    networks:
      - app-network
    volumes:
      - ./backend:/var/www/html
    expose:
      - 8000
      - 9000
      - 9003
    env_file:
      - .env
    depends_on:
      - database
    environment:
      PHP_IDE_CONFIG: "serverName=fourgen.dev"
      DB_DRIVER: ${DB_DRIVER}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_CHARSET: ${DB_CHARSET}
      APP_DEBUG: ${APP_DEBUG}
      APP_ENV: ${APP_ENV}

  proxy:
    image: nginx:alpine
    container_name: proxy
    restart: always
    networks:
      - app-network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend:/var/www/html
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - backend

  database:
    image: mysql:8.0
    container_name: database
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - ./db/db_storage:/var/lib/mysql
      - ./db/init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost', '-u', 'root', '-p${DB_ROOT_PASSWORD}']
      interval: 5s
      timeout: 5s
      retries: 10

networks:
  app-network:
    driver: bridge

