FROM php:8.4-fpm

RUN pecl install xdebug
# Copia tu configuración personalizada de Xdebug
COPY ./xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini


# Dependencias necesarias para composer
RUN apt-get update && apt-get install -y curl git unzip zip nodejs npm libmariadb-dev \
  libonig-dev libzip-dev && rm -rf /var/lib/apt/lists/*
RUN docker-php-ext-install pdo_mysql bcmath mbstring exif pcntl opcache zip

# Instalación de composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN composer global require laravel/installer
RUN export PATH="$PATH:$HOME/.composer/vendor/bin"

# Configurar directorio de trabajo
WORKDIR /var/www/html

